Homework 1
================
Salah El-Sadek

Homework 1 Solution.

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------------------------------------------------------------------------- tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.3     v dplyr   1.0.2
    ## v tidyr   1.1.2     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts ---------------------------------------------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

# Question 1

Creating the data frame.

``` r
q1_df =
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
  )
```

Taking the mean of each variable in the data frame.

``` r
mean(pull(q1_df, samp))
```

    ## [1] -0.004185038

``` r
mean(pull(q1_df, samp_gt_0))
```

    ## [1] 0.6

``` r
mean(pull(q1_df, char_vec))
```

    ## Warning in mean.default(pull(q1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(q1_df, factor_vec))
```

    ## Warning in mean.default(pull(q1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I can take the mean of numbers or logical, but not of characters and
factors.

``` r
as.numeric(pull(q1_df, samp))
```

    ##  [1]  0.9894859 -1.0813032 -1.2947773  0.3933706 -0.2022384  0.7589749
    ##  [7]  0.4939166 -1.0342334  0.5667664  0.3681875

``` r
as.numeric(pull(q1_df, samp_gt_0))
```

    ##  [1] 1 0 0 1 0 1 1 0 1 1

``` r
as.numeric(pull(q1_df, char_vec))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(q1_df, factor_vec))
```

    ##  [1] 2 2 2 3 3 3 3 1 1 1

I can change factors and logical into numerical, but not characters.

``` r
as.numeric(pull(q1_df, samp_gt_0)) * pull(q1_df, samp)
```

    ##  [1] 0.9894859 0.0000000 0.0000000 0.3933706 0.0000000 0.7589749 0.4939166
    ##  [8] 0.0000000 0.5667664 0.3681875

``` r
as.factor(pull(q1_df, samp_gt_0)) * pull(q1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(q1_df, samp_gt_0)), pull(q1_df, samp)): '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(q1_df, samp_gt_0))) * pull(q1_df, samp)
```

    ##  [1]  1.9789718 -1.0813032 -1.2947773  0.7867411 -0.2022384  1.5179499
    ##  [7]  0.9878333 -1.0342334  1.1335328  0.7363751

It seems that you cannot multiply factors, and have to convert them to
numeric to meaningfully multiply them.

# Question 2

``` r
data("penguins", package = "palmerpenguins")
```

This seems to be a data set describing penguin characteristics such as
bill length/depth, flipper length, and body mass of different species of
penguins, identifying which island said penguins come from. Data on sex
(either male or female) of penguins and year that the data on each
penguin was recorded is also available in the data set.

``` r
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

There are 8 columns and 344 rows in the penguin data set.

``` r
mean((pull(penguins, flipper_length_mm)), na.rm=TRUE)
```

    ## [1] 200.9152

The mean flipper length of penguins in the data set (excluding those
without flipper length data) is 200.9152.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_sne2114_files/figure-gfm/ggplot-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", height = 4, width = 8)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
